### ISSUE TITLE
Improve LaTeX builder

### ISSUE THREAD

**Issue by veli-m-andirin** [JMSLab/Template#42]
In this issue we aim to have a working LaTeX builder that can also handle bibliographies and cross-references.

**Comment by rcalvo12** [comment]
@jmshapir, I just wrapped up my first pass at the improved latex builder (!!!!!!!!) but need write access to share my results.

**Comment by jmshapir** [comment]
> @jmshapir, I just wrapped up my first pass at the improved latex builder (!!!!!!!!) but need write access to share my results.

@rcalvo12 done, thanks!

**Comment by rcalvo12** [comment]
In 402c380 I produced my first pass at the improved latex builder. I appreciate everyone's patience on this. Changes were made in branch `issue42_latex_builder`.

The previous latex builder actually wasn't too far off, and after adjusting some fields in the latex file I could produce a pdf from a latex file that included external tables and graphs, footnotes, and a handwritten reference section. The main changes here were to make sure that the files referenced within the latex file were referenced from root of the directory. For example, instead of calling a table with `\input{../output/tables/top_gdp}` you call it with `\input{output/tables/top_gdp}`. You can see examples in the `TemplateTest.tex` file. 

However, with the previous version of the builder, we could not use a .bib file to produce a bibliography.

The updated builder uses the following sequence to compile the latex files:
```
pdflatex -> bibtex -> pdflatex -> pdflatex
```
If you go to the `/issue42/` directory, delete everything except `References.bib`, `TemplateTest.tex`, and `Sconscript`, and then run `scons` from the root of the repository you can see that it produces the sample pdf with the proper references.

Looking forward to iterating on next versions.

**Comment by jmshapir** [comment]
Thanks @rcalvo12 and nice work! I was able to compile the issue folder successfully on my first try. :-)

A few things:
* I think we should add Template.tex to /souce/paper. (That way users of JMSLab/Template have an easy choice between TeX and LyX.)
* I think we should add References.bib to /source/paper, and we should revise Template.lyx to use BibTeX for references. (I'm inclined to move the lab towards using BibTeX more universally.)
* I think we should update `test_build_latex.py` to test the current instantiation of the builder.

From my standpoint, once we've done those things, you can open a pull request with @veli-m-andirin @jmshapir as reviewers. (At that point we can also see if @mcaceresb wants to review.)

**Comment by rcalvo12** [comment]
> * I think we should add Template.tex to /souce/paper. (That way users of JMSLab/Template have an easy choice between TeX and LyX.)
> * I think we should add References.bib to /source/paper, and we should revise Template.lyx to use BibTeX for references. (I'm inclined to move the lab towards using BibTeX more universally.)
> * I think we should update `test_build_latex.py` to test the current instantiation of the builder.

@jmshapir I moved Template.tex and References.bib to /source/paper and I have revised Template.lyx to use BibTeX for references. I also modified sconscript files so that outputs for both Template.tex and Template.lyx are sent to /output/paper when scons is run at the root of the directory. 

As far as updating `test_build_latex.py`, I'm not sure what extra tests we would need here or which tests would need to be modified. It seems to me that the way `test_build_latex.py` is constructed would still work, though I may be wrong about that.

**Comment by jmshapir** [comment]
> As far as updating `test_build_latex.py`, I'm not sure what extra tests we would need here or which tests would need to be modified. It seems to me that the way `test_build_latex.py` is constructed would still work, though I may be wrong about that.

@rcalvo12 thanks! If the existing unit tests for `build_latex` still work, and cover the main elements we're testing for in the unit tests for our other builders, then we should be all set here. Just wanted to make sure unit tests are functioning and up to date for this revised builder!

**Comment by rcalvo12** [comment]
@jmshapir Checking it against some of the other builders, and keeping in mind the changes that were made, I think we should probably be fine with the current test. I can flag this as a point for review in the PR though since, again I might be missing something. With that in mind, do you think we're ready for a PR on this?

**Comment by jmshapir** [comment]
@rcalvo12 sounds good and yes!

**Comment by rcalvo12** [comment]
Thread continues in PR #56.

**Comment by rcalvo12** [comment]
Summary:

In this issue we fixed our LaTeX builder so that we can now use scons to convert LaTeX files to PDF, including LaTeX files with corresponding bibtex files for references. Paper's are compiled in the following way under the surface:

```
pdflatex -> pdflatex -> pdflatex #No Bibtex
pdflatex -> bibtex -> pdflatex -> pdflatex #With Bibtex
```

We also added testing for the LaTeX builder and the bibtex functionality.

Final state of issue branch [here](https://github.com/JMSLab/Template/tree/3710921502e0e46307ca1104fe5653a92ef3effe).
