### ISSUE TITLE
Discuss use of submodule for library

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/Template#61]
I'm opening this issue to discuss whether we might like to make `/source/lib/JMSLab` a standalone repository that is imported in `Template` as a submodule. For background see [github blog](https://github.blog/2016-02-01-working-with-submodules/), [git docs](https://git-scm.com/book/en/v2/Git-Tools-Submodules), [gist](https://gist.github.com/gitaarik/8735255).

I'm assinging to @veli-m-andirin @rcalvo12 but anyone who has a view should feel free to weigh in!

**Comment by veli-m-andirin** [comment]
Thanks @jmshapir!

Here are my thoughts about this:

- I tried to think of the advantages that using submodules can bring:
   - I agree with the two points mentioned in [gist](https://gist.github.com/gitaarik/8735255), although I think the first point is not very relevant for us. (`Template` is not a huge repository, and `source/lib/JMSLab` makes a small part of it, so taking it out would not help the Template a lot. Moreover, most of our development efforts here is focused on `source/lib/JMSLab`, so we do not really have a pollution of commit history, i.e., majority of the commits concern that directory.)
   - In terms of the second point, here are my thoughts: The fact that people will not have to manually copy-paste the builders when we update them sounds nice. However, this also does not mean that any changes in submodules will be reflected in parent repositories automatically. `git pull` does not automatically update submodules, so one has to run `git submodule update`. I think this would require every user of a repository to do the same thing since `git pull` won't update the submodule for them either. Hence, there is still manual effort required, and that can become more complicated with every user having to enter an additional command rather than `git pull`. 
- In terms of the downsides:
   - One thing that I appreciate about current architecture is that having copies of the builders in each repository also allows us to modify them depending on the needs of a project. (Consider the case we want to tweak some builders or modify executable names in a project but not in others.) I wondered if this functionality would be preserved if we use submodules. The answer is yes, but things seem to require additional care as [per the discussion here](https://stackoverflow.com/questions/5427414/editing-a-git-submodule).
   - Moreover, per the section "Switching to submodules" [here](https://github.blog/2016-02-01-working-with-submodules/), taking out an existing folder to become an external dependency requires some more effort compared to a clean start. 
   - This is minor, but I don't know how well this functionality is represented in GitHub Desktop. When cloning a repository with submodules or updating submodules within a repository, the most basic commands such as `git clone` or `git pull` are not sufficient, so switching to submodules might require everyone to use the command-line client from time to time. 

Overall, I think both the costs and the benefits are small, and I think the costs slightly exceed the benefits. (Or at least, the benefits don't seem large enough to necessitate a move.)

Curious to know your thoughts @jmshapir @rcalvo12.

**Comment by jmshapir** [comment]
@veli-m-andirin thanks! [That](https://github.com/JMSLab/Template/issues/61#issuecomment-1121260359) sounds reasonable to me. I'll leave the issue open for a bit in case anyone has thoughts to add. Also, to be clear, this isn't pressing--just wanted to open the discussion while I was thinking about it.

**Comment by jmshapir** [comment]
Summary: In this issue we considered transitioning the python library in the `Template` to a submodule. Since no one has advocated in favor I am closing the issue, but we can reopen if someone wishes to take the other side!
