### ISSUE TITLE
Modify builders to routinely output more granular timestamps

### ISSUE THREAD

**Issue by zhizhongpu** [JMSLab/Template#96]
We would like to record each code file's run time, which we hope to be reflected in `sconscript.log`. 

Currently, `sconscript.log` only documents the starting time when the entire SCons process starts, and the ending time when the specific source folder finishes running. For example, under output/dir1 we may have a log file that begins with:

> *** Builder log created: {2099-03-28 17:35:28}
> *** Builder log completed: {2099-03-28 23:51:54}

while under output/dir2 we have a log file that begins with:

> *** Builder log created: {2099-03-28 17:35:28}
> *** Builder log completed: {2099-03-29 00:22:35}

**Comment by jmshapir** [comment]
@zhizhongpu do you think it would be very valuable for us to have timestamps for each script?

If so, please feel free to keep this open and work on it when you can. If not, please close.

Thanks!

**Comment by jmshapir** [comment]
**Summary: ** In this issue we considered modifying builders to output more granular timestamp information at the level of the individual process rather than the individual `SConscript`. We decided not to pursue this now but may pick it back up again in future if we find use cases where the value would be very high.
